version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db3:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network
  server:
    build:
      context: ./
      dockerfile: ./packages/server/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 1546:1546
    tty: true
    networks:
      - app-network
  admin:
    build:
      context: ./
      dockerfile: ./packages/admin/Dockerfile
    volumes:
      - .:/projects
    ports:
      - 3000:3000
    tty: true
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
